NUM_NODES=3
MAX_NUM_NODES=5
NODE_PREFIX=testcont

LXD_PROFILE=testcont  # auto creation
LXD_POOL=default   # use an existing storage pool

LXD_NET1_NAME=testcont1  # auto creation
LXD_NET1_PREFIX="10.99.88."
LXD_NET1_DHCP_RANGE="100-250"
NGINX_VIP_ADDR="${LXD_NET1_PREFIX}50"

INSTANCE_PREFIX=nginx-lb-

LXD_REMOTE_TMP_PASSWORD=68157562-fa93-11ed-8c10-00155dc8aa19

# for LXD VMs (base machine)
IMAGE=ubuntu:22.04

# for LXD containers
CONT_IMAGE_ALIAS=22.04
CONT_IMAGE=ubuntu:${CONT_IMAGE_ALIAS}

USERNAME=ubuntu

MICROK8S_VERSION=1.26/stable

HTTP_PROXY=
HTTPS_PROXY=

USE_VM=true

LIMIT_CPU=1
LIMIT_MEMORY=2500MiB
