version: "3"
services:
  web:
    image: nginx
    deploy:
      #mode: global
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "50080:80"
    #networks:
    #  - testwebnet
#networks:
#  testwebnet:
