---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbot
  labels:
    app: microbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microbot
  template:
    metadata:
      labels:
        app: microbot
    spec:
      containers:
        - name: microbot
          image: dontrebootme/microbot:v1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.5"
              memory: "200Mi"
          ports:
            - name: http-80
              containerPort: 80
              #hostPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: microbot
spec:
  ports:
    - name: http-80
      port: 80
      nodePort: 32080
  selector:
    app: microbot
  type: NodePort
